locales:
  srs:
    name: Tsuutʼina Keyboards
    description: >-
      Mobile OS keyboards for the Tsuutʼina language from the Divvun group
      at UiT.
  en:
    name: Tsuutʼina Keyboards
    description: >-
      Mobile OS keyboards for the Tsuutʼina language from the Divvun group
      at UiT.
  nb:
    name: Tsuutʼina tastatur
    description: Mobiltastatur for Tsuutʼina fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
